/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreatePeopleInput = {
  id?: string | null,
  caseNumber?: string | null,
  firstName?: string | null,
  lastName?: string | null,
  missingAge?: number | null,
  city?: string | null,
  county?: string | null,
  state?: string | null,
  sex?: string | null,
  race?: string | null,
  dateModified?: string | null,
  imageFilename?: string | null,
  imagePath?: string | null,
  agencyAddress?: string | null,
  agencyCaseNumber?: string | null,
  agencyCounty?: string | null,
  agencyDateReported?: string | null,
  agencyGeneralEmail?: string | null,
  agencyInvestigator?: string | null,
  agencyJurisdiction?: string | null,
  agencyMainPhone?: string | null,
  agencyName?: string | null,
  agencyNotes?: string | null,
  agencyOri?: string | null,
  agencyType?: string | null,
  agencyWebsiteURL?: string | null,
  bodyHairDescription?: string | null,
  circumstancesOfDisappearance?: string | null,
  currentAge?: number | null,
  dateOfLastContact?: string | null,
  dlc?: string | null,
  eyeDescription?: string | null,
  facialHairDescription?: string | null,
  hairColor?: string | null,
  headHairDescription?: string | null,
  height?: string | null,
  leftEyeColor?: string | null,
  location?: string | null,
  middleName?: string | null,
  namusCaseCreated?: string | null,
  namusContactName?: string | null,
  namusEmail?: string | null,
  namusPhoneNumber?: string | null,
  nickname?: string | null,
  rightEyeColor?: string | null,
  weight?: string | null,
};

export type ModelPeopleConditionInput = {
  caseNumber?: ModelStringInput | null,
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  missingAge?: ModelIntInput | null,
  city?: ModelStringInput | null,
  county?: ModelStringInput | null,
  state?: ModelStringInput | null,
  sex?: ModelStringInput | null,
  race?: ModelStringInput | null,
  dateModified?: ModelStringInput | null,
  imageFilename?: ModelStringInput | null,
  imagePath?: ModelStringInput | null,
  agencyAddress?: ModelStringInput | null,
  agencyCaseNumber?: ModelStringInput | null,
  agencyCounty?: ModelStringInput | null,
  agencyDateReported?: ModelStringInput | null,
  agencyGeneralEmail?: ModelStringInput | null,
  agencyInvestigator?: ModelStringInput | null,
  agencyJurisdiction?: ModelStringInput | null,
  agencyMainPhone?: ModelStringInput | null,
  agencyName?: ModelStringInput | null,
  agencyNotes?: ModelStringInput | null,
  agencyOri?: ModelStringInput | null,
  agencyType?: ModelStringInput | null,
  agencyWebsiteURL?: ModelStringInput | null,
  bodyHairDescription?: ModelStringInput | null,
  circumstancesOfDisappearance?: ModelStringInput | null,
  currentAge?: ModelIntInput | null,
  dateOfLastContact?: ModelStringInput | null,
  dlc?: ModelStringInput | null,
  eyeDescription?: ModelStringInput | null,
  facialHairDescription?: ModelStringInput | null,
  hairColor?: ModelStringInput | null,
  headHairDescription?: ModelStringInput | null,
  height?: ModelStringInput | null,
  leftEyeColor?: ModelStringInput | null,
  location?: ModelStringInput | null,
  middleName?: ModelStringInput | null,
  namusCaseCreated?: ModelStringInput | null,
  namusContactName?: ModelStringInput | null,
  namusEmail?: ModelStringInput | null,
  namusPhoneNumber?: ModelStringInput | null,
  nickname?: ModelStringInput | null,
  rightEyeColor?: ModelStringInput | null,
  weight?: ModelStringInput | null,
  and?: Array< ModelPeopleConditionInput | null > | null,
  or?: Array< ModelPeopleConditionInput | null > | null,
  not?: ModelPeopleConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type UpdatePeopleInput = {
  id: string,
  caseNumber?: string | null,
  firstName?: string | null,
  lastName?: string | null,
  missingAge?: number | null,
  city?: string | null,
  county?: string | null,
  state?: string | null,
  sex?: string | null,
  race?: string | null,
  dateModified?: string | null,
  imageFilename?: string | null,
  imagePath?: string | null,
  agencyAddress?: string | null,
  agencyCaseNumber?: string | null,
  agencyCounty?: string | null,
  agencyDateReported?: string | null,
  agencyGeneralEmail?: string | null,
  agencyInvestigator?: string | null,
  agencyJurisdiction?: string | null,
  agencyMainPhone?: string | null,
  agencyName?: string | null,
  agencyNotes?: string | null,
  agencyOri?: string | null,
  agencyType?: string | null,
  agencyWebsiteURL?: string | null,
  bodyHairDescription?: string | null,
  circumstancesOfDisappearance?: string | null,
  currentAge?: number | null,
  dateOfLastContact?: string | null,
  dlc?: string | null,
  eyeDescription?: string | null,
  facialHairDescription?: string | null,
  hairColor?: string | null,
  headHairDescription?: string | null,
  height?: string | null,
  leftEyeColor?: string | null,
  location?: string | null,
  middleName?: string | null,
  namusCaseCreated?: string | null,
  namusContactName?: string | null,
  namusEmail?: string | null,
  namusPhoneNumber?: string | null,
  nickname?: string | null,
  rightEyeColor?: string | null,
  weight?: string | null,
};

export type DeletePeopleInput = {
  id?: string | null,
};

export type CreateFaceVectorInput = {
  id?: string | null,
  vector?: string | null,
};

export type ModelFaceVectorConditionInput = {
  vector?: ModelStringInput | null,
  and?: Array< ModelFaceVectorConditionInput | null > | null,
  or?: Array< ModelFaceVectorConditionInput | null > | null,
  not?: ModelFaceVectorConditionInput | null,
};

export type UpdateFaceVectorInput = {
  id: string,
  vector?: string | null,
};

export type DeleteFaceVectorInput = {
  id?: string | null,
};

export type ModelPeopleFilterInput = {
  id?: ModelIDInput | null,
  caseNumber?: ModelStringInput | null,
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  missingAge?: ModelIntInput | null,
  city?: ModelStringInput | null,
  county?: ModelStringInput | null,
  state?: ModelStringInput | null,
  sex?: ModelStringInput | null,
  race?: ModelStringInput | null,
  dateModified?: ModelStringInput | null,
  imageFilename?: ModelStringInput | null,
  imagePath?: ModelStringInput | null,
  agencyAddress?: ModelStringInput | null,
  agencyCaseNumber?: ModelStringInput | null,
  agencyCounty?: ModelStringInput | null,
  agencyDateReported?: ModelStringInput | null,
  agencyGeneralEmail?: ModelStringInput | null,
  agencyInvestigator?: ModelStringInput | null,
  agencyJurisdiction?: ModelStringInput | null,
  agencyMainPhone?: ModelStringInput | null,
  agencyName?: ModelStringInput | null,
  agencyNotes?: ModelStringInput | null,
  agencyOri?: ModelStringInput | null,
  agencyType?: ModelStringInput | null,
  agencyWebsiteURL?: ModelStringInput | null,
  bodyHairDescription?: ModelStringInput | null,
  circumstancesOfDisappearance?: ModelStringInput | null,
  currentAge?: ModelIntInput | null,
  dateOfLastContact?: ModelStringInput | null,
  dlc?: ModelStringInput | null,
  eyeDescription?: ModelStringInput | null,
  facialHairDescription?: ModelStringInput | null,
  hairColor?: ModelStringInput | null,
  headHairDescription?: ModelStringInput | null,
  height?: ModelStringInput | null,
  leftEyeColor?: ModelStringInput | null,
  location?: ModelStringInput | null,
  middleName?: ModelStringInput | null,
  namusCaseCreated?: ModelStringInput | null,
  namusContactName?: ModelStringInput | null,
  namusEmail?: ModelStringInput | null,
  namusPhoneNumber?: ModelStringInput | null,
  nickname?: ModelStringInput | null,
  rightEyeColor?: ModelStringInput | null,
  weight?: ModelStringInput | null,
  and?: Array< ModelPeopleFilterInput | null > | null,
  or?: Array< ModelPeopleFilterInput | null > | null,
  not?: ModelPeopleFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelFaceVectorFilterInput = {
  id?: ModelIDInput | null,
  vector?: ModelStringInput | null,
  and?: Array< ModelFaceVectorFilterInput | null > | null,
  or?: Array< ModelFaceVectorFilterInput | null > | null,
  not?: ModelFaceVectorFilterInput | null,
};

export type CreatePeopleMutationVariables = {
  input: CreatePeopleInput,
  condition?: ModelPeopleConditionInput | null,
};

export type CreatePeopleMutation = {
  createPeople:  {
    __typename: "People",
    id: string,
    caseNumber: string | null,
    firstName: string | null,
    lastName: string | null,
    missingAge: number | null,
    city: string | null,
    county: string | null,
    state: string | null,
    sex: string | null,
    race: string | null,
    dateModified: string | null,
    imageFilename: string | null,
    imagePath: string | null,
    faceVector:  Array< {
      __typename: "FaceVector",
      id: string,
      person:  {
        __typename: "People",
        id: string,
        caseNumber: string | null,
        firstName: string | null,
        lastName: string | null,
        missingAge: number | null,
        city: string | null,
        county: string | null,
        state: string | null,
        sex: string | null,
        race: string | null,
        dateModified: string | null,
        imageFilename: string | null,
        imagePath: string | null,
        agencyAddress: string | null,
        agencyCaseNumber: string | null,
        agencyCounty: string | null,
        agencyDateReported: string | null,
        agencyGeneralEmail: string | null,
        agencyInvestigator: string | null,
        agencyJurisdiction: string | null,
        agencyMainPhone: string | null,
        agencyName: string | null,
        agencyNotes: string | null,
        agencyOri: string | null,
        agencyType: string | null,
        agencyWebsiteURL: string | null,
        bodyHairDescription: string | null,
        circumstancesOfDisappearance: string | null,
        currentAge: number | null,
        dateOfLastContact: string | null,
        dlc: string | null,
        eyeDescription: string | null,
        facialHairDescription: string | null,
        hairColor: string | null,
        headHairDescription: string | null,
        height: string | null,
        leftEyeColor: string | null,
        location: string | null,
        middleName: string | null,
        namusCaseCreated: string | null,
        namusContactName: string | null,
        namusEmail: string | null,
        namusPhoneNumber: string | null,
        nickname: string | null,
        rightEyeColor: string | null,
        weight: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      vector: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    agencyAddress: string | null,
    agencyCaseNumber: string | null,
    agencyCounty: string | null,
    agencyDateReported: string | null,
    agencyGeneralEmail: string | null,
    agencyInvestigator: string | null,
    agencyJurisdiction: string | null,
    agencyMainPhone: string | null,
    agencyName: string | null,
    agencyNotes: string | null,
    agencyOri: string | null,
    agencyType: string | null,
    agencyWebsiteURL: string | null,
    bodyHairDescription: string | null,
    circumstancesOfDisappearance: string | null,
    currentAge: number | null,
    dateOfLastContact: string | null,
    dlc: string | null,
    eyeDescription: string | null,
    facialHairDescription: string | null,
    hairColor: string | null,
    headHairDescription: string | null,
    height: string | null,
    leftEyeColor: string | null,
    location: string | null,
    middleName: string | null,
    namusCaseCreated: string | null,
    namusContactName: string | null,
    namusEmail: string | null,
    namusPhoneNumber: string | null,
    nickname: string | null,
    rightEyeColor: string | null,
    weight: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdatePeopleMutationVariables = {
  input: UpdatePeopleInput,
  condition?: ModelPeopleConditionInput | null,
};

export type UpdatePeopleMutation = {
  updatePeople:  {
    __typename: "People",
    id: string,
    caseNumber: string | null,
    firstName: string | null,
    lastName: string | null,
    missingAge: number | null,
    city: string | null,
    county: string | null,
    state: string | null,
    sex: string | null,
    race: string | null,
    dateModified: string | null,
    imageFilename: string | null,
    imagePath: string | null,
    faceVector:  Array< {
      __typename: "FaceVector",
      id: string,
      person:  {
        __typename: "People",
        id: string,
        caseNumber: string | null,
        firstName: string | null,
        lastName: string | null,
        missingAge: number | null,
        city: string | null,
        county: string | null,
        state: string | null,
        sex: string | null,
        race: string | null,
        dateModified: string | null,
        imageFilename: string | null,
        imagePath: string | null,
        agencyAddress: string | null,
        agencyCaseNumber: string | null,
        agencyCounty: string | null,
        agencyDateReported: string | null,
        agencyGeneralEmail: string | null,
        agencyInvestigator: string | null,
        agencyJurisdiction: string | null,
        agencyMainPhone: string | null,
        agencyName: string | null,
        agencyNotes: string | null,
        agencyOri: string | null,
        agencyType: string | null,
        agencyWebsiteURL: string | null,
        bodyHairDescription: string | null,
        circumstancesOfDisappearance: string | null,
        currentAge: number | null,
        dateOfLastContact: string | null,
        dlc: string | null,
        eyeDescription: string | null,
        facialHairDescription: string | null,
        hairColor: string | null,
        headHairDescription: string | null,
        height: string | null,
        leftEyeColor: string | null,
        location: string | null,
        middleName: string | null,
        namusCaseCreated: string | null,
        namusContactName: string | null,
        namusEmail: string | null,
        namusPhoneNumber: string | null,
        nickname: string | null,
        rightEyeColor: string | null,
        weight: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      vector: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    agencyAddress: string | null,
    agencyCaseNumber: string | null,
    agencyCounty: string | null,
    agencyDateReported: string | null,
    agencyGeneralEmail: string | null,
    agencyInvestigator: string | null,
    agencyJurisdiction: string | null,
    agencyMainPhone: string | null,
    agencyName: string | null,
    agencyNotes: string | null,
    agencyOri: string | null,
    agencyType: string | null,
    agencyWebsiteURL: string | null,
    bodyHairDescription: string | null,
    circumstancesOfDisappearance: string | null,
    currentAge: number | null,
    dateOfLastContact: string | null,
    dlc: string | null,
    eyeDescription: string | null,
    facialHairDescription: string | null,
    hairColor: string | null,
    headHairDescription: string | null,
    height: string | null,
    leftEyeColor: string | null,
    location: string | null,
    middleName: string | null,
    namusCaseCreated: string | null,
    namusContactName: string | null,
    namusEmail: string | null,
    namusPhoneNumber: string | null,
    nickname: string | null,
    rightEyeColor: string | null,
    weight: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeletePeopleMutationVariables = {
  input: DeletePeopleInput,
  condition?: ModelPeopleConditionInput | null,
};

export type DeletePeopleMutation = {
  deletePeople:  {
    __typename: "People",
    id: string,
    caseNumber: string | null,
    firstName: string | null,
    lastName: string | null,
    missingAge: number | null,
    city: string | null,
    county: string | null,
    state: string | null,
    sex: string | null,
    race: string | null,
    dateModified: string | null,
    imageFilename: string | null,
    imagePath: string | null,
    faceVector:  Array< {
      __typename: "FaceVector",
      id: string,
      person:  {
        __typename: "People",
        id: string,
        caseNumber: string | null,
        firstName: string | null,
        lastName: string | null,
        missingAge: number | null,
        city: string | null,
        county: string | null,
        state: string | null,
        sex: string | null,
        race: string | null,
        dateModified: string | null,
        imageFilename: string | null,
        imagePath: string | null,
        agencyAddress: string | null,
        agencyCaseNumber: string | null,
        agencyCounty: string | null,
        agencyDateReported: string | null,
        agencyGeneralEmail: string | null,
        agencyInvestigator: string | null,
        agencyJurisdiction: string | null,
        agencyMainPhone: string | null,
        agencyName: string | null,
        agencyNotes: string | null,
        agencyOri: string | null,
        agencyType: string | null,
        agencyWebsiteURL: string | null,
        bodyHairDescription: string | null,
        circumstancesOfDisappearance: string | null,
        currentAge: number | null,
        dateOfLastContact: string | null,
        dlc: string | null,
        eyeDescription: string | null,
        facialHairDescription: string | null,
        hairColor: string | null,
        headHairDescription: string | null,
        height: string | null,
        leftEyeColor: string | null,
        location: string | null,
        middleName: string | null,
        namusCaseCreated: string | null,
        namusContactName: string | null,
        namusEmail: string | null,
        namusPhoneNumber: string | null,
        nickname: string | null,
        rightEyeColor: string | null,
        weight: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      vector: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    agencyAddress: string | null,
    agencyCaseNumber: string | null,
    agencyCounty: string | null,
    agencyDateReported: string | null,
    agencyGeneralEmail: string | null,
    agencyInvestigator: string | null,
    agencyJurisdiction: string | null,
    agencyMainPhone: string | null,
    agencyName: string | null,
    agencyNotes: string | null,
    agencyOri: string | null,
    agencyType: string | null,
    agencyWebsiteURL: string | null,
    bodyHairDescription: string | null,
    circumstancesOfDisappearance: string | null,
    currentAge: number | null,
    dateOfLastContact: string | null,
    dlc: string | null,
    eyeDescription: string | null,
    facialHairDescription: string | null,
    hairColor: string | null,
    headHairDescription: string | null,
    height: string | null,
    leftEyeColor: string | null,
    location: string | null,
    middleName: string | null,
    namusCaseCreated: string | null,
    namusContactName: string | null,
    namusEmail: string | null,
    namusPhoneNumber: string | null,
    nickname: string | null,
    rightEyeColor: string | null,
    weight: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateFaceVectorMutationVariables = {
  input: CreateFaceVectorInput,
  condition?: ModelFaceVectorConditionInput | null,
};

export type CreateFaceVectorMutation = {
  createFaceVector:  {
    __typename: "FaceVector",
    id: string,
    person:  {
      __typename: "People",
      id: string,
      caseNumber: string | null,
      firstName: string | null,
      lastName: string | null,
      missingAge: number | null,
      city: string | null,
      county: string | null,
      state: string | null,
      sex: string | null,
      race: string | null,
      dateModified: string | null,
      imageFilename: string | null,
      imagePath: string | null,
      faceVector:  Array< {
        __typename: "FaceVector",
        id: string,
        vector: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      agencyAddress: string | null,
      agencyCaseNumber: string | null,
      agencyCounty: string | null,
      agencyDateReported: string | null,
      agencyGeneralEmail: string | null,
      agencyInvestigator: string | null,
      agencyJurisdiction: string | null,
      agencyMainPhone: string | null,
      agencyName: string | null,
      agencyNotes: string | null,
      agencyOri: string | null,
      agencyType: string | null,
      agencyWebsiteURL: string | null,
      bodyHairDescription: string | null,
      circumstancesOfDisappearance: string | null,
      currentAge: number | null,
      dateOfLastContact: string | null,
      dlc: string | null,
      eyeDescription: string | null,
      facialHairDescription: string | null,
      hairColor: string | null,
      headHairDescription: string | null,
      height: string | null,
      leftEyeColor: string | null,
      location: string | null,
      middleName: string | null,
      namusCaseCreated: string | null,
      namusContactName: string | null,
      namusEmail: string | null,
      namusPhoneNumber: string | null,
      nickname: string | null,
      rightEyeColor: string | null,
      weight: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    vector: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateFaceVectorMutationVariables = {
  input: UpdateFaceVectorInput,
  condition?: ModelFaceVectorConditionInput | null,
};

export type UpdateFaceVectorMutation = {
  updateFaceVector:  {
    __typename: "FaceVector",
    id: string,
    person:  {
      __typename: "People",
      id: string,
      caseNumber: string | null,
      firstName: string | null,
      lastName: string | null,
      missingAge: number | null,
      city: string | null,
      county: string | null,
      state: string | null,
      sex: string | null,
      race: string | null,
      dateModified: string | null,
      imageFilename: string | null,
      imagePath: string | null,
      faceVector:  Array< {
        __typename: "FaceVector",
        id: string,
        vector: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      agencyAddress: string | null,
      agencyCaseNumber: string | null,
      agencyCounty: string | null,
      agencyDateReported: string | null,
      agencyGeneralEmail: string | null,
      agencyInvestigator: string | null,
      agencyJurisdiction: string | null,
      agencyMainPhone: string | null,
      agencyName: string | null,
      agencyNotes: string | null,
      agencyOri: string | null,
      agencyType: string | null,
      agencyWebsiteURL: string | null,
      bodyHairDescription: string | null,
      circumstancesOfDisappearance: string | null,
      currentAge: number | null,
      dateOfLastContact: string | null,
      dlc: string | null,
      eyeDescription: string | null,
      facialHairDescription: string | null,
      hairColor: string | null,
      headHairDescription: string | null,
      height: string | null,
      leftEyeColor: string | null,
      location: string | null,
      middleName: string | null,
      namusCaseCreated: string | null,
      namusContactName: string | null,
      namusEmail: string | null,
      namusPhoneNumber: string | null,
      nickname: string | null,
      rightEyeColor: string | null,
      weight: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    vector: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteFaceVectorMutationVariables = {
  input: DeleteFaceVectorInput,
  condition?: ModelFaceVectorConditionInput | null,
};

export type DeleteFaceVectorMutation = {
  deleteFaceVector:  {
    __typename: "FaceVector",
    id: string,
    person:  {
      __typename: "People",
      id: string,
      caseNumber: string | null,
      firstName: string | null,
      lastName: string | null,
      missingAge: number | null,
      city: string | null,
      county: string | null,
      state: string | null,
      sex: string | null,
      race: string | null,
      dateModified: string | null,
      imageFilename: string | null,
      imagePath: string | null,
      faceVector:  Array< {
        __typename: "FaceVector",
        id: string,
        vector: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      agencyAddress: string | null,
      agencyCaseNumber: string | null,
      agencyCounty: string | null,
      agencyDateReported: string | null,
      agencyGeneralEmail: string | null,
      agencyInvestigator: string | null,
      agencyJurisdiction: string | null,
      agencyMainPhone: string | null,
      agencyName: string | null,
      agencyNotes: string | null,
      agencyOri: string | null,
      agencyType: string | null,
      agencyWebsiteURL: string | null,
      bodyHairDescription: string | null,
      circumstancesOfDisappearance: string | null,
      currentAge: number | null,
      dateOfLastContact: string | null,
      dlc: string | null,
      eyeDescription: string | null,
      facialHairDescription: string | null,
      hairColor: string | null,
      headHairDescription: string | null,
      height: string | null,
      leftEyeColor: string | null,
      location: string | null,
      middleName: string | null,
      namusCaseCreated: string | null,
      namusContactName: string | null,
      namusEmail: string | null,
      namusPhoneNumber: string | null,
      nickname: string | null,
      rightEyeColor: string | null,
      weight: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    vector: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetPeopleQueryVariables = {
  id: string,
};

export type GetPeopleQuery = {
  getPeople:  {
    __typename: "People",
    id: string,
    caseNumber: string | null,
    firstName: string | null,
    lastName: string | null,
    missingAge: number | null,
    city: string | null,
    county: string | null,
    state: string | null,
    sex: string | null,
    race: string | null,
    dateModified: string | null,
    imageFilename: string | null,
    imagePath: string | null,
    faceVector:  Array< {
      __typename: "FaceVector",
      id: string,
      person:  {
        __typename: "People",
        id: string,
        caseNumber: string | null,
        firstName: string | null,
        lastName: string | null,
        missingAge: number | null,
        city: string | null,
        county: string | null,
        state: string | null,
        sex: string | null,
        race: string | null,
        dateModified: string | null,
        imageFilename: string | null,
        imagePath: string | null,
        agencyAddress: string | null,
        agencyCaseNumber: string | null,
        agencyCounty: string | null,
        agencyDateReported: string | null,
        agencyGeneralEmail: string | null,
        agencyInvestigator: string | null,
        agencyJurisdiction: string | null,
        agencyMainPhone: string | null,
        agencyName: string | null,
        agencyNotes: string | null,
        agencyOri: string | null,
        agencyType: string | null,
        agencyWebsiteURL: string | null,
        bodyHairDescription: string | null,
        circumstancesOfDisappearance: string | null,
        currentAge: number | null,
        dateOfLastContact: string | null,
        dlc: string | null,
        eyeDescription: string | null,
        facialHairDescription: string | null,
        hairColor: string | null,
        headHairDescription: string | null,
        height: string | null,
        leftEyeColor: string | null,
        location: string | null,
        middleName: string | null,
        namusCaseCreated: string | null,
        namusContactName: string | null,
        namusEmail: string | null,
        namusPhoneNumber: string | null,
        nickname: string | null,
        rightEyeColor: string | null,
        weight: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      vector: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    agencyAddress: string | null,
    agencyCaseNumber: string | null,
    agencyCounty: string | null,
    agencyDateReported: string | null,
    agencyGeneralEmail: string | null,
    agencyInvestigator: string | null,
    agencyJurisdiction: string | null,
    agencyMainPhone: string | null,
    agencyName: string | null,
    agencyNotes: string | null,
    agencyOri: string | null,
    agencyType: string | null,
    agencyWebsiteURL: string | null,
    bodyHairDescription: string | null,
    circumstancesOfDisappearance: string | null,
    currentAge: number | null,
    dateOfLastContact: string | null,
    dlc: string | null,
    eyeDescription: string | null,
    facialHairDescription: string | null,
    hairColor: string | null,
    headHairDescription: string | null,
    height: string | null,
    leftEyeColor: string | null,
    location: string | null,
    middleName: string | null,
    namusCaseCreated: string | null,
    namusContactName: string | null,
    namusEmail: string | null,
    namusPhoneNumber: string | null,
    nickname: string | null,
    rightEyeColor: string | null,
    weight: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListPeoplesQueryVariables = {
  filter?: ModelPeopleFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListPeoplesQuery = {
  listPeoples:  {
    __typename: "ModelPeopleConnection",
    items:  Array< {
      __typename: "People",
      id: string,
      caseNumber: string | null,
      firstName: string | null,
      lastName: string | null,
      missingAge: number | null,
      city: string | null,
      county: string | null,
      state: string | null,
      sex: string | null,
      race: string | null,
      dateModified: string | null,
      imageFilename: string | null,
      imagePath: string | null,
      faceVector:  Array< {
        __typename: "FaceVector",
        id: string,
        vector: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      agencyAddress: string | null,
      agencyCaseNumber: string | null,
      agencyCounty: string | null,
      agencyDateReported: string | null,
      agencyGeneralEmail: string | null,
      agencyInvestigator: string | null,
      agencyJurisdiction: string | null,
      agencyMainPhone: string | null,
      agencyName: string | null,
      agencyNotes: string | null,
      agencyOri: string | null,
      agencyType: string | null,
      agencyWebsiteURL: string | null,
      bodyHairDescription: string | null,
      circumstancesOfDisappearance: string | null,
      currentAge: number | null,
      dateOfLastContact: string | null,
      dlc: string | null,
      eyeDescription: string | null,
      facialHairDescription: string | null,
      hairColor: string | null,
      headHairDescription: string | null,
      height: string | null,
      leftEyeColor: string | null,
      location: string | null,
      middleName: string | null,
      namusCaseCreated: string | null,
      namusContactName: string | null,
      namusEmail: string | null,
      namusPhoneNumber: string | null,
      nickname: string | null,
      rightEyeColor: string | null,
      weight: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetFaceVectorQueryVariables = {
  id: string,
};

export type GetFaceVectorQuery = {
  getFaceVector:  {
    __typename: "FaceVector",
    id: string,
    person:  {
      __typename: "People",
      id: string,
      caseNumber: string | null,
      firstName: string | null,
      lastName: string | null,
      missingAge: number | null,
      city: string | null,
      county: string | null,
      state: string | null,
      sex: string | null,
      race: string | null,
      dateModified: string | null,
      imageFilename: string | null,
      imagePath: string | null,
      faceVector:  Array< {
        __typename: "FaceVector",
        id: string,
        vector: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      agencyAddress: string | null,
      agencyCaseNumber: string | null,
      agencyCounty: string | null,
      agencyDateReported: string | null,
      agencyGeneralEmail: string | null,
      agencyInvestigator: string | null,
      agencyJurisdiction: string | null,
      agencyMainPhone: string | null,
      agencyName: string | null,
      agencyNotes: string | null,
      agencyOri: string | null,
      agencyType: string | null,
      agencyWebsiteURL: string | null,
      bodyHairDescription: string | null,
      circumstancesOfDisappearance: string | null,
      currentAge: number | null,
      dateOfLastContact: string | null,
      dlc: string | null,
      eyeDescription: string | null,
      facialHairDescription: string | null,
      hairColor: string | null,
      headHairDescription: string | null,
      height: string | null,
      leftEyeColor: string | null,
      location: string | null,
      middleName: string | null,
      namusCaseCreated: string | null,
      namusContactName: string | null,
      namusEmail: string | null,
      namusPhoneNumber: string | null,
      nickname: string | null,
      rightEyeColor: string | null,
      weight: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    vector: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListFaceVectorsQueryVariables = {
  filter?: ModelFaceVectorFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListFaceVectorsQuery = {
  listFaceVectors:  {
    __typename: "ModelFaceVectorConnection",
    items:  Array< {
      __typename: "FaceVector",
      id: string,
      person:  {
        __typename: "People",
        id: string,
        caseNumber: string | null,
        firstName: string | null,
        lastName: string | null,
        missingAge: number | null,
        city: string | null,
        county: string | null,
        state: string | null,
        sex: string | null,
        race: string | null,
        dateModified: string | null,
        imageFilename: string | null,
        imagePath: string | null,
        agencyAddress: string | null,
        agencyCaseNumber: string | null,
        agencyCounty: string | null,
        agencyDateReported: string | null,
        agencyGeneralEmail: string | null,
        agencyInvestigator: string | null,
        agencyJurisdiction: string | null,
        agencyMainPhone: string | null,
        agencyName: string | null,
        agencyNotes: string | null,
        agencyOri: string | null,
        agencyType: string | null,
        agencyWebsiteURL: string | null,
        bodyHairDescription: string | null,
        circumstancesOfDisappearance: string | null,
        currentAge: number | null,
        dateOfLastContact: string | null,
        dlc: string | null,
        eyeDescription: string | null,
        facialHairDescription: string | null,
        hairColor: string | null,
        headHairDescription: string | null,
        height: string | null,
        leftEyeColor: string | null,
        location: string | null,
        middleName: string | null,
        namusCaseCreated: string | null,
        namusContactName: string | null,
        namusEmail: string | null,
        namusPhoneNumber: string | null,
        nickname: string | null,
        rightEyeColor: string | null,
        weight: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      vector: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type OnCreatePeopleSubscription = {
  onCreatePeople:  {
    __typename: "People",
    id: string,
    caseNumber: string | null,
    firstName: string | null,
    lastName: string | null,
    missingAge: number | null,
    city: string | null,
    county: string | null,
    state: string | null,
    sex: string | null,
    race: string | null,
    dateModified: string | null,
    imageFilename: string | null,
    imagePath: string | null,
    faceVector:  Array< {
      __typename: "FaceVector",
      id: string,
      person:  {
        __typename: "People",
        id: string,
        caseNumber: string | null,
        firstName: string | null,
        lastName: string | null,
        missingAge: number | null,
        city: string | null,
        county: string | null,
        state: string | null,
        sex: string | null,
        race: string | null,
        dateModified: string | null,
        imageFilename: string | null,
        imagePath: string | null,
        agencyAddress: string | null,
        agencyCaseNumber: string | null,
        agencyCounty: string | null,
        agencyDateReported: string | null,
        agencyGeneralEmail: string | null,
        agencyInvestigator: string | null,
        agencyJurisdiction: string | null,
        agencyMainPhone: string | null,
        agencyName: string | null,
        agencyNotes: string | null,
        agencyOri: string | null,
        agencyType: string | null,
        agencyWebsiteURL: string | null,
        bodyHairDescription: string | null,
        circumstancesOfDisappearance: string | null,
        currentAge: number | null,
        dateOfLastContact: string | null,
        dlc: string | null,
        eyeDescription: string | null,
        facialHairDescription: string | null,
        hairColor: string | null,
        headHairDescription: string | null,
        height: string | null,
        leftEyeColor: string | null,
        location: string | null,
        middleName: string | null,
        namusCaseCreated: string | null,
        namusContactName: string | null,
        namusEmail: string | null,
        namusPhoneNumber: string | null,
        nickname: string | null,
        rightEyeColor: string | null,
        weight: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      vector: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    agencyAddress: string | null,
    agencyCaseNumber: string | null,
    agencyCounty: string | null,
    agencyDateReported: string | null,
    agencyGeneralEmail: string | null,
    agencyInvestigator: string | null,
    agencyJurisdiction: string | null,
    agencyMainPhone: string | null,
    agencyName: string | null,
    agencyNotes: string | null,
    agencyOri: string | null,
    agencyType: string | null,
    agencyWebsiteURL: string | null,
    bodyHairDescription: string | null,
    circumstancesOfDisappearance: string | null,
    currentAge: number | null,
    dateOfLastContact: string | null,
    dlc: string | null,
    eyeDescription: string | null,
    facialHairDescription: string | null,
    hairColor: string | null,
    headHairDescription: string | null,
    height: string | null,
    leftEyeColor: string | null,
    location: string | null,
    middleName: string | null,
    namusCaseCreated: string | null,
    namusContactName: string | null,
    namusEmail: string | null,
    namusPhoneNumber: string | null,
    nickname: string | null,
    rightEyeColor: string | null,
    weight: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdatePeopleSubscription = {
  onUpdatePeople:  {
    __typename: "People",
    id: string,
    caseNumber: string | null,
    firstName: string | null,
    lastName: string | null,
    missingAge: number | null,
    city: string | null,
    county: string | null,
    state: string | null,
    sex: string | null,
    race: string | null,
    dateModified: string | null,
    imageFilename: string | null,
    imagePath: string | null,
    faceVector:  Array< {
      __typename: "FaceVector",
      id: string,
      person:  {
        __typename: "People",
        id: string,
        caseNumber: string | null,
        firstName: string | null,
        lastName: string | null,
        missingAge: number | null,
        city: string | null,
        county: string | null,
        state: string | null,
        sex: string | null,
        race: string | null,
        dateModified: string | null,
        imageFilename: string | null,
        imagePath: string | null,
        agencyAddress: string | null,
        agencyCaseNumber: string | null,
        agencyCounty: string | null,
        agencyDateReported: string | null,
        agencyGeneralEmail: string | null,
        agencyInvestigator: string | null,
        agencyJurisdiction: string | null,
        agencyMainPhone: string | null,
        agencyName: string | null,
        agencyNotes: string | null,
        agencyOri: string | null,
        agencyType: string | null,
        agencyWebsiteURL: string | null,
        bodyHairDescription: string | null,
        circumstancesOfDisappearance: string | null,
        currentAge: number | null,
        dateOfLastContact: string | null,
        dlc: string | null,
        eyeDescription: string | null,
        facialHairDescription: string | null,
        hairColor: string | null,
        headHairDescription: string | null,
        height: string | null,
        leftEyeColor: string | null,
        location: string | null,
        middleName: string | null,
        namusCaseCreated: string | null,
        namusContactName: string | null,
        namusEmail: string | null,
        namusPhoneNumber: string | null,
        nickname: string | null,
        rightEyeColor: string | null,
        weight: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      vector: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    agencyAddress: string | null,
    agencyCaseNumber: string | null,
    agencyCounty: string | null,
    agencyDateReported: string | null,
    agencyGeneralEmail: string | null,
    agencyInvestigator: string | null,
    agencyJurisdiction: string | null,
    agencyMainPhone: string | null,
    agencyName: string | null,
    agencyNotes: string | null,
    agencyOri: string | null,
    agencyType: string | null,
    agencyWebsiteURL: string | null,
    bodyHairDescription: string | null,
    circumstancesOfDisappearance: string | null,
    currentAge: number | null,
    dateOfLastContact: string | null,
    dlc: string | null,
    eyeDescription: string | null,
    facialHairDescription: string | null,
    hairColor: string | null,
    headHairDescription: string | null,
    height: string | null,
    leftEyeColor: string | null,
    location: string | null,
    middleName: string | null,
    namusCaseCreated: string | null,
    namusContactName: string | null,
    namusEmail: string | null,
    namusPhoneNumber: string | null,
    nickname: string | null,
    rightEyeColor: string | null,
    weight: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeletePeopleSubscription = {
  onDeletePeople:  {
    __typename: "People",
    id: string,
    caseNumber: string | null,
    firstName: string | null,
    lastName: string | null,
    missingAge: number | null,
    city: string | null,
    county: string | null,
    state: string | null,
    sex: string | null,
    race: string | null,
    dateModified: string | null,
    imageFilename: string | null,
    imagePath: string | null,
    faceVector:  Array< {
      __typename: "FaceVector",
      id: string,
      person:  {
        __typename: "People",
        id: string,
        caseNumber: string | null,
        firstName: string | null,
        lastName: string | null,
        missingAge: number | null,
        city: string | null,
        county: string | null,
        state: string | null,
        sex: string | null,
        race: string | null,
        dateModified: string | null,
        imageFilename: string | null,
        imagePath: string | null,
        agencyAddress: string | null,
        agencyCaseNumber: string | null,
        agencyCounty: string | null,
        agencyDateReported: string | null,
        agencyGeneralEmail: string | null,
        agencyInvestigator: string | null,
        agencyJurisdiction: string | null,
        agencyMainPhone: string | null,
        agencyName: string | null,
        agencyNotes: string | null,
        agencyOri: string | null,
        agencyType: string | null,
        agencyWebsiteURL: string | null,
        bodyHairDescription: string | null,
        circumstancesOfDisappearance: string | null,
        currentAge: number | null,
        dateOfLastContact: string | null,
        dlc: string | null,
        eyeDescription: string | null,
        facialHairDescription: string | null,
        hairColor: string | null,
        headHairDescription: string | null,
        height: string | null,
        leftEyeColor: string | null,
        location: string | null,
        middleName: string | null,
        namusCaseCreated: string | null,
        namusContactName: string | null,
        namusEmail: string | null,
        namusPhoneNumber: string | null,
        nickname: string | null,
        rightEyeColor: string | null,
        weight: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      vector: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    agencyAddress: string | null,
    agencyCaseNumber: string | null,
    agencyCounty: string | null,
    agencyDateReported: string | null,
    agencyGeneralEmail: string | null,
    agencyInvestigator: string | null,
    agencyJurisdiction: string | null,
    agencyMainPhone: string | null,
    agencyName: string | null,
    agencyNotes: string | null,
    agencyOri: string | null,
    agencyType: string | null,
    agencyWebsiteURL: string | null,
    bodyHairDescription: string | null,
    circumstancesOfDisappearance: string | null,
    currentAge: number | null,
    dateOfLastContact: string | null,
    dlc: string | null,
    eyeDescription: string | null,
    facialHairDescription: string | null,
    hairColor: string | null,
    headHairDescription: string | null,
    height: string | null,
    leftEyeColor: string | null,
    location: string | null,
    middleName: string | null,
    namusCaseCreated: string | null,
    namusContactName: string | null,
    namusEmail: string | null,
    namusPhoneNumber: string | null,
    nickname: string | null,
    rightEyeColor: string | null,
    weight: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateFaceVectorSubscription = {
  onCreateFaceVector:  {
    __typename: "FaceVector",
    id: string,
    person:  {
      __typename: "People",
      id: string,
      caseNumber: string | null,
      firstName: string | null,
      lastName: string | null,
      missingAge: number | null,
      city: string | null,
      county: string | null,
      state: string | null,
      sex: string | null,
      race: string | null,
      dateModified: string | null,
      imageFilename: string | null,
      imagePath: string | null,
      faceVector:  Array< {
        __typename: "FaceVector",
        id: string,
        vector: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      agencyAddress: string | null,
      agencyCaseNumber: string | null,
      agencyCounty: string | null,
      agencyDateReported: string | null,
      agencyGeneralEmail: string | null,
      agencyInvestigator: string | null,
      agencyJurisdiction: string | null,
      agencyMainPhone: string | null,
      agencyName: string | null,
      agencyNotes: string | null,
      agencyOri: string | null,
      agencyType: string | null,
      agencyWebsiteURL: string | null,
      bodyHairDescription: string | null,
      circumstancesOfDisappearance: string | null,
      currentAge: number | null,
      dateOfLastContact: string | null,
      dlc: string | null,
      eyeDescription: string | null,
      facialHairDescription: string | null,
      hairColor: string | null,
      headHairDescription: string | null,
      height: string | null,
      leftEyeColor: string | null,
      location: string | null,
      middleName: string | null,
      namusCaseCreated: string | null,
      namusContactName: string | null,
      namusEmail: string | null,
      namusPhoneNumber: string | null,
      nickname: string | null,
      rightEyeColor: string | null,
      weight: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    vector: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateFaceVectorSubscription = {
  onUpdateFaceVector:  {
    __typename: "FaceVector",
    id: string,
    person:  {
      __typename: "People",
      id: string,
      caseNumber: string | null,
      firstName: string | null,
      lastName: string | null,
      missingAge: number | null,
      city: string | null,
      county: string | null,
      state: string | null,
      sex: string | null,
      race: string | null,
      dateModified: string | null,
      imageFilename: string | null,
      imagePath: string | null,
      faceVector:  Array< {
        __typename: "FaceVector",
        id: string,
        vector: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      agencyAddress: string | null,
      agencyCaseNumber: string | null,
      agencyCounty: string | null,
      agencyDateReported: string | null,
      agencyGeneralEmail: string | null,
      agencyInvestigator: string | null,
      agencyJurisdiction: string | null,
      agencyMainPhone: string | null,
      agencyName: string | null,
      agencyNotes: string | null,
      agencyOri: string | null,
      agencyType: string | null,
      agencyWebsiteURL: string | null,
      bodyHairDescription: string | null,
      circumstancesOfDisappearance: string | null,
      currentAge: number | null,
      dateOfLastContact: string | null,
      dlc: string | null,
      eyeDescription: string | null,
      facialHairDescription: string | null,
      hairColor: string | null,
      headHairDescription: string | null,
      height: string | null,
      leftEyeColor: string | null,
      location: string | null,
      middleName: string | null,
      namusCaseCreated: string | null,
      namusContactName: string | null,
      namusEmail: string | null,
      namusPhoneNumber: string | null,
      nickname: string | null,
      rightEyeColor: string | null,
      weight: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    vector: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteFaceVectorSubscription = {
  onDeleteFaceVector:  {
    __typename: "FaceVector",
    id: string,
    person:  {
      __typename: "People",
      id: string,
      caseNumber: string | null,
      firstName: string | null,
      lastName: string | null,
      missingAge: number | null,
      city: string | null,
      county: string | null,
      state: string | null,
      sex: string | null,
      race: string | null,
      dateModified: string | null,
      imageFilename: string | null,
      imagePath: string | null,
      faceVector:  Array< {
        __typename: "FaceVector",
        id: string,
        vector: string | null,
        createdAt: string,
        updatedAt: string,
      } | null > | null,
      agencyAddress: string | null,
      agencyCaseNumber: string | null,
      agencyCounty: string | null,
      agencyDateReported: string | null,
      agencyGeneralEmail: string | null,
      agencyInvestigator: string | null,
      agencyJurisdiction: string | null,
      agencyMainPhone: string | null,
      agencyName: string | null,
      agencyNotes: string | null,
      agencyOri: string | null,
      agencyType: string | null,
      agencyWebsiteURL: string | null,
      bodyHairDescription: string | null,
      circumstancesOfDisappearance: string | null,
      currentAge: number | null,
      dateOfLastContact: string | null,
      dlc: string | null,
      eyeDescription: string | null,
      facialHairDescription: string | null,
      hairColor: string | null,
      headHairDescription: string | null,
      height: string | null,
      leftEyeColor: string | null,
      location: string | null,
      middleName: string | null,
      namusCaseCreated: string | null,
      namusContactName: string | null,
      namusEmail: string | null,
      namusPhoneNumber: string | null,
      nickname: string | null,
      rightEyeColor: string | null,
      weight: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    vector: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
